url: https://cti-summit.org
permalink: /:categories/:title
exclude: [vendor]
repository: circl/cti-summit
future: true
timezone: Europe/Luxembourg 
sass:
  sass_dir: assets/_scss
include:
  - .well-known
keep_files:
  - .dat
  - dat.json
